version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  expo:
    build: .
    command: sh -c "cd /app/frontend && npm install && expo start --tunnel"
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"

volumes:
  postgres_data:
